const CREATE_TASK = "CREATE_TASK",
	DELETE_TASK = "DELETE_TASK",
	MODIFY_TASK_DES = "MODIFY_TASK_DES",
	MODIFY_TASK_STATUS = "MODIFY_TASK_STATUS",
	MODIFY_TASK_DUE = "MODIFY_TASK_DUE",
	ASSIGN_TASK = "ASSIGN_TASK",
	WATCH_TASK = "WATCH_TASK",
	//comment
	ADD_COMMENT = "ADD_COMMENT",
	REMOVE_COMMENT = "REMOVE_COMMENT",
	MODIFY_COMMENT = "MODIFY_COMMENT",
	REPLY_COMMENT = "REPLY_COMMENT",
	//file
	UPLOAD_FILE = "UPLOAD_FILE",
	DELETE_FILE = "DELETE_FILE";

export default {
	CREATE_TASK,
	DELETE_TASK,
	MODIFY_TASK_DES,
	MODIFY_TASK_STATUS,
	MODIFY_TASK_DUE,
	ASSIGN_TASK,
	WATCH_TASK,
	ADD_COMMENT,
	REMOVE_COMMENT,
	MODIFY_COMMENT,
	REPLY_COMMENT,
	UPLOAD_FILE,
	DELETE_FILE,
};
//TODO: to be continued
