export const NEW_TASK_FORM_ACTION = {
	ON_NEW_TASK_SUBMIT: "ON_NEW_TASK_SUBMIT",
	ON_NEW_TASK_TITLE_CHANGE: "ON_NEW_TASK_TITLE_CHANGE",
	ON_NEW_TASK_DESCRIPTION_CHANGE: "ON_NEW_TASK_DESCRIPTION_CHANGE",
	ON_NEW_TASK_ASSIGNEEID_CHANGE: "ON_NEW_TASK_ASSIGNEEID_CHANGE",
	ON_NEW_TASK_DUEDATE_CHANGE: "ON_NEW_TASK_DUEDATE_CHANGE",
	ON_NEW_TASK_SEARCH_CHANGE: "ON_NEW_TASK_SEARCH_CHANGE",
	ON_NEW_TASK_SEARCH_REQUEST: "ON_NEW_TASK_SEARCH_REQUEST",
	ON_NEW_TASK_SEARCH_BLUR: "ON_NEW_TASK_SEARCH_BLUR",
	ON_NEW_TASK_SEARCH_FOCUS: "ON_NEW_TASK_SEARCH_FOCUS",
};

export const NAV_SEARCH_BOX_ACTION = {
	ON_ITEM_CLICK: "ON_ITEM_CLICK",
};
