export const SET_TASK_DETAIL_ITEM = "SET_TASK_DETAIL_ITEM";
export const SET_TASK_DETAIL_EDITABLE_ITEM = "SET_TASK_DETAIL_EDITABLE_ITEM";
export const SET_EDITING_STATUS_KEY = "SET_EDITING_STATUS_KEY";
export const SET_EDITING_KEY_VALUE_PAIR = "SET_EDITING_KEY_VALUE_PAIR";
export const RESET_EDITOR_STATUS = "RESET_EDITOR_STATUS";
